k

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -254,30 +254,25 @@ jobs:
 
 
   run-migrations:
-    docker:
-      - image: cimg/base:stable
+    docker: 
+      - image: mareimorsy/aws-node
+
     steps:
       - checkout
-      - install_nodejs
-      - install_aws_cli
       - run:
           name: Run migrations
           command: |
+            # export TYPEORM_HOST=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
             cd backend
             npm install
             npm run premigrations
-            npm run migrations > migrations_dump.txt
-            cat migrations_dump.txt
-      - run:
-          name: Send migration results to kvdb.io
-          command: |
-            if (grep -q "has been excuted successfully." ~/project/backend/migrations_dump.txt \
-            || grep -q "No migrations are pending" ~/project/backend/migrations_dump.txt)
-            then
-              curl https://kvdb.io/${KVDB_BUCKET}/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
-            fi
-      - destroy-environment
-      - revert-migrations
+            npm run migrations
+      # - run:
+      #     name: Send migration results to memstash
+      #     command: |
+      #       # Your code here
+      #       exit 1
+     # Here's where you will add some code to rollback on failure  
 
 
   deploy-frontend:
