alaaa

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -404,29 +404,28 @@ jobs:
       - destroy-environment
       - revert-migrations
 
-  smoke-test:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      # - checkout
-      - run:
-          name: Backend smoke test.
-          command: |
-            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+  # smoke-test:
+  #   docker:
+  #     - image: amazon/aws-cli
+  #   steps:
+  #     # - checkout
+  #     - run:
+  #         name: Backend smoke test.
+  #         command: |
+  #           export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
             
-            # URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
-            URL="http://g00gle.com"
-            if curl -s --head ${URL}
-            then
-              echo "It worked!"
-              exit 0
-            else
-              echo "Rolling Back"
-              exit 1
-            fi
-
-      - notify_on_failure
-      - destroy_environment
+  #           # URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+  #           URL="http://g00gle.com"
+  #           if curl -s --head ${URL}
+  #           then
+  #             echo "It worked!"
+  #             exit 0
+  #           else
+  #             echo "Rolling Back"
+  #             exit 1
+  #           fi
+  #     - notify_on_failure
+  #     - destroy_environment
 
   # smoke-test:
   #   docker:
@@ -465,101 +464,164 @@ jobs:
   #     - destroy-environment
   #     - revert-migrations
 
+  # cloudfront-update:
+  #   docker:
+  #     - image: cimg/base:stable
+  #   steps:
+  #     - checkout
+  #     - install_aws_cli
+  #     - install_nodejs
+  #     - run:
+  #         name: Save old workflow ID
+  #         command: |
+  #           export OLD_WORKFLOW_ID=$(aws cloudformation \
+  #           list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+  #           --no-paginate --output text)
+  #           echo "Old workflow ID: $OLD_WORKFLOW_ID"
+  #           curl https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d $OLD_WORKFLOW_ID 
+  #     - run:
+  #         name: Update cloudfront distribution
+  #         command: |
+  #           aws cloudformation deploy \
+  #           --template-file .circleci/files/cloudfront.yml \
+  #           --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+  #           --stack-name "Initial-Stack"
+  #     - destroy-environment
+  #     - revert-migrations
+
+  # cleanup:
+  #     docker:
+  #       - image: cimg/base:stable
+  #     steps:
+  #       - checkout
+  #       - install_aws_cli
+  #       - install_nodejs
+  #       - run:
+  #           name: Cleanup old stacks
+  #           command: |
+  #             # First: Get old stack workflow id
+  #             export OldWorkflowID=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/old_workflow_id)
+  #             echo "Old workflow ID: $OldWorkflowID"
+  #             # Then: Get stacks list
+  #             export STACKS=($(aws cloudformation list-stacks \
+  #             --query "StackSummaries[*].StackName" \
+  #             --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+  #             echo Stacks list: "${STACKS[@]}"
+  #             # Finally: Remove old stacks
+  #             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+  #             then
+  #               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+  #               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+  #               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+  #             fi
+  # notify_on_success:
+  #   docker:
+  #     - image: cimg/base:stable
+  #   steps:
+  #     - slack/notify:
+  #         event: pass
+  #         channel: cicd-udacity-project
+  #         template: success_tagged_deploy_1
+
+smoke-test:
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      # - checkout
+      - run:
+          name: Backend smoke test.
+          command: |
+            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+            # URL="http://g00gle.com"
+            if curl -s --head ${URL}
+            then
+              echo "It worked!"
+              exit 0
+            else
+              echo "Rolling Back"
+              exit 1
+            fi
+      - notify_on_failure
+      - destroy_environment
+      - revert-migrations
+
   cloudfront-update:
     docker:
-      - image: cimg/base:stable
+      - image: mareimorsy/aws-node
     steps:
       - checkout
-      - install_aws_cli
-      - install_nodejs
       - run:
-          name: Save old workflow ID
+          name: Save Old Workflow ID to kvdb.io
           command: |
             export OLD_WORKFLOW_ID=$(aws cloudformation \
-            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-            --no-paginate --output text)
-            echo "Old workflow ID: $OLD_WORKFLOW_ID"
-            curl https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d $OLD_WORKFLOW_ID 
+                      --region us-east-1 \
+                      list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                      --no-paginate --output text)
+            echo "Old Wokflow ID: $OLD_WORKFLOW_ID"
+            curl -k https://kvdb.io/${KVDB_BUCKET}/old_workflow_id -d "${OLD_WORKFLOW_ID}"
       - run:
           name: Update cloudfront distribution
           command: |
             aws cloudformation deploy \
-            --template-file .circleci/files/cloudfront.yml \
-            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-            --stack-name "Initial-Stack"
-      - destroy-environment
-      - revert-migrations
-
-  cleanup:
-      docker:
-        - image: cimg/base:stable
-      steps:
-        - checkout
-        - install_aws_cli
-        - install_nodejs
-        - run:
-            name: Cleanup old stacks
-            command: |
-              # First: Get old stack workflow id
-              export OldWorkflowID=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/old_workflow_id)
-              echo "Old workflow ID: $OldWorkflowID"
-              # Then: Get stacks list
-              export STACKS=($(aws cloudformation list-stacks \
-              --query "StackSummaries[*].StackName" \
-              --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
-              echo Stacks list: "${STACKS[@]}"
-              # Finally: Remove old stacks
-              if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-              then
-                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-                aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-              fi
-  notify_on_success:
+              --template-file .circleci/files/cloudfront.yml \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
+              --region us-east-1 \
+              --stack-name InitialStack
+cleanup:
     docker:
-      - image: cimg/base:stable
+      - image: mareimorsy/aws-node
     steps:
-      - slack/notify:
-          event: pass
-          channel: cicd-udacity-project
-          template: success_tagged_deploy_1
-
-workflows:  # create workflows
+      - checkout
+      - run:
+          name: Remove old stacks and files
+          command: |
+            export OldWorkflowID=$(aws cloudformation \
+            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+            --no-paginate --output text)
+            export STACKS=($(aws cloudformation list-stacks \
+                --query "StackSummaries[*].StackName" \
+                --stack-status-filter CREATE_COMPLETE \
+                --region us-east-1 \
+                --no-paginate --output text)) 
+            export OldWorkflowID=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/old_workflow_id)
+            echo Stack names: "${STACKS[@]}"
+            echo Old Workflow ID: $OldWorkflowID 
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              aws s3 rm s3://udapeople-${OldWorkflowID} --recursive
+              aws cloudformation delete-stack --stack-name --region us-east-1  "backend"
+              aws cloudformation delete-stack --stack-name --region us-east-1 "frontend"
+            fi
+workflows:
   default:
     jobs:
-      - build-frontend
-      - build-backend
-      - test-frontend:
+     - build-frontend
+     - build-backend
+     - test-frontend:
          requires: [build-frontend]
-      - test-backend:
+     - test-backend:
          requires: [build-backend]
-      - scan-backend:
-          requires: [build-backend]
-      - scan-frontend:
-          requires: [build-frontend]
-      - notify_on_success:
-         requires:
-         - test-frontend
-         - test-backend
-         - scan-frontend
-         - scan-backend    
-
-      - deploy-infrastructure:
-          # requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-          filters:
-            branches:
-              only: [master]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [deploy-infrastructure]
-      - deploy-backend:
-          requires: [run-migrations]
-      - smoke-test:
-           requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
+     - scan-backend:
+         requires: [build-backend]
+     - scan-frontend:
+         requires: [build-frontend]
+     - deploy-infrastructure:
+         requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+         filters:
+           branches:
+             only: [master]
+     - configure-infrastructure:
+         requires: [deploy-infrastructure]
+     - run-migrations:
+         requires: [configure-infrastructure]
+     - deploy-frontend:
+         requires: [run-migrations]
+     - deploy-backend:
+         requires: [run-migrations]
+     - smoke-test:
+         requires: [deploy-backend, deploy-frontend]
+     - cloudfront-update:
           requires: [smoke-test]
-      - cleanup:
+     - cleanup:
           requires: [cloudfront-update]
